### ISSUE TITLE
Generating XPath expressions

### ISSUE THREAD

**Issue by matthewmcgarvey** [naqvis/crystal-xpath2#1]
This shard is specifically for parsing xpath expressions and finding xml nodes with them, so I'm wondering if it would make sense to also have the ability to generate the xpath expressions with a DSL of sorts?

I'm thinking of an API like https://github.com/teamcapybara/xpath

I am using some expressions from a ruby gem and they are using this library so I have to run the code to generate the string representation and make a string constant in my crystal code. The resulting xpath query is very complicated but the DSL is fairly understandable.

**Comment by naqvis** [comment]
This shard performs the parsing , compilation of XPath expressions and evaluate those expressions via its abstract interface `NodeNavigator` which is use-case agnostics. Libraries plan to implement XPath support only need to implement `NodeNavigator` interface. specs of this shard comes with dummy implementation for this interface.  Shards [crystal-html5](https://github.com/naqvis/crystal-html5) and [json-xpath](https://github.com/naqvis/json-xpath) both uses this shard and have implementation specific to them.

Libraries using this shard doesn't need to expose API of this shard on their side. Implementing DSL like API will require its user libraries to expose this shard API on their side, as well as make its usage somewhat complicated for them (this shard user libraries).

I believe DSL or XPath expression builder like functionality is good candidate for a separate shard, which can help users define their XPath expressions via DSL or similar mechanims and then provide a method to get XPath expression in string format.
